config/routes.rb
::Refinery::Application.routes.draw do

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :pods, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/pod.rb
class Pod < ActiveRecord::Base

  POD_TYPES = %w(content banner gallery video)

  acts_as_indexed :fields => [:name, :body, :url]

  validates_presence_of :name
  validates_inclusion_of :pod_type, :in => POD_TYPES

  belongs_to :image
  belongs_to :portfolio_entry
  belongs_to :video
  has_and_belongs_to_many :pages

  def system_name
    pod_type
  end

end

app/models/refinery/pods/pod.rb
module Refinery
  module Pods
    class Pod < Refinery::Core::BaseModel
      self.table_name = 'refinery_pods'

      POD_TYPES = %w(content banner gallery video inquiry)

      acts_as_indexed :fields => [:name, :body, :url, :pod_type]

      validates_presence_of :name
      validates_inclusion_of :pod_type, :in => POD_TYPES
          
      belongs_to :image, :class_name => '::Refinery::Image'

      belongs_to :portfolio_entry, :class_name => '::Refinery::Portfolio::Gallery'
      belongs_to :video, :class_name => '::Refinery::Videos::Video'
      has_and_belongs_to_many :pages, :class_name => '::Refinery::Page', :join_table => 'refinery_pages_pods'

      def system_name
        pod_type
      end

    end
  end
end

app/controllers/admin/pods_controller.rb
module Admin
  class PodsController < Admin::BaseController

    crudify :pod,
            :title_attribute => 'name', :xhr_paging => true

  end
end

app/controllers/refinery/pods/admin/pods_controller.rb
module Refinery
  module Pods
    module Admin
      class PodsController < ::Refinery::AdminController

        crudify :'refinery/pods/pod',
                :title_attribute => 'name'
                
        private

        def pod_params
        	params.require(:pod).permit([:name, :body, :url, :image_id, :pod_type, :portfolio_entry_id, :video_id, :position, :page_ids])
        end

      end
    end
  end
end

app/views/admin/pods/_actions.html.erb
<ul>
  <% if Admin::PodsController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_pods_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_pod_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::PodsController.sortable? and Pod.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Pods"),
                 admin_pods_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Pods"),
                 admin_pods_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/pods/_form.html.erb
<%= form_for [:admin, @pod] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @pod,
          :include_object_name => true
        } %>

  <%= hidden_field_tag 'pod[page_ids][]' %>

  <div class='field'>
    <%= f.label :pod_type -%>
    <%#= f.collection_select :pod_type_id, PodType.order(:name), :id , :name, {:prompt => "-- Please select --"}, {} -%>
    <%= f.select :pod_type, Pod::POD_TYPES, {:include_blank => true} %>
  </div>

  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
      <ul id='page_parts'>
        <% [:body].each_with_index do |part, part_index| %>
          <li class='ui-state-default<%= ' ui-state-active' if part_index == 0 %>'>
            <%= link_to part.to_s.titleize, "##{part}" %>
          </li>
        <% end %>
      </ul>

      <div id='page_part_editors'>
        <% [:body].each do |part| %>
          <div class='page_part' id='<%= part %>'>
            <%= f.text_area part, :rows => 20, :class => 'wymeditor widest' -%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class='field'>
    <%= f.label :url -%>
    <%= f.text_field :url  -%>
  </div>
  
  <div class='field'>
    <%= f.label :image -%>
    <%= render :partial => "/shared/admin/image_picker", :locals => {
          :f => f,
          :field => :image_id,
          :image => @pod.image,
          :toggle_image_display => false
        } %>
  </div>
  

  <div class='field'>
    <%= f.label :portfolio_entry_id, 'Gallery' -%>
    <%= f.collection_select :portfolio_entry_id, PortfolioEntry.order(:title), :id , :title, {:prompt => "-- Please select when relevant --"}, {} -%>
  </div>
  
  <div class='field'>
    <%= f.label :video_id -%>
    <%= f.collection_select :video_id, Video.order(:name), :id , :name, {:prompt => "-- Please select when relevant --"}, {} -%>
  </div>

  <div class="field">
    <%= f.label :pages %>
    <% for page in Page.find(:all) %>
      <div>
        <%= check_box_tag "pod[page_ids][]", page.id, @pod.pages.include?(page) %>
        <%= page.title %>
      </div>
    <% end %>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.pods.pod'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @pod.name)
              } %>
<% end -%>
<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      page_options.init(false, '', '');
    });
  </script>
<% end %>

app/views/admin/pods/_pod.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(pod) -%>">
  <span class='title'>
    <%= pod.name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_pod_path(pod),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_pod_path(pod),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => pod.name),
        :method => :delete %>
  </span>
</li>

app/views/admin/pods/_pods.html.erb
<%= will_paginate @pods %>
<%= render :partial => "sortable_list" %>

app/views/admin/pods/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @pods.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'pods' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/pods/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'pod', :collection => @pods %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/pods/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/pods/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::PodsController.sortable? and Pod.count > 1 %>

app/views/admin/pods/new.html.erb
<%= render :partial => "form" %>

app/views/refinery/pods/admin/pods/_form.html.erb
<%= form_for [refinery, :pods_admin, @pod] do |f| -%>
  <%= render '/refinery/admin/error_messages',
              :object => @pod,
              :include_object_name => true %>

  <%= hidden_field_tag 'pod[page_ids][]' %>

  <div class='field'>
    <%= f.label :pod_type -%>
    <%= f.select :pod_type, ::Refinery::Pods::Pod::POD_TYPES, {:include_blank => true} %>
  </div>

  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest'  -%>

  </div>
  
  <div class='field'>
    <div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
      <ul id='page_parts'>
        <% [:body].each_with_index do |part, part_index| %>
          <li class='ui-state-default<%= ' ui-state-active' if part_index == 0 %>'>
            <%= link_to t("#{part}", :scope => "activerecord.attributes.refinery/pods/pod", :default => part.to_s.titleize), "##{part}" %>
          </li>
        <% end %>
      </ul>
      <div id='page_part_editors'>
        <% [:body].each do |part| %>
          <div class='page_part' id='<%= part %>'>
            <%= f.text_area part, :rows => 20, :class => 'wymeditor widest' -%>
          </div>
        <% end %>
      </div>
    </div>

  </div>
  
  <div class='field'>
    <%= f.label :url -%>
    <%= f.text_field :url  -%>

  </div>
  
  <div class='field'>
    <%= f.label :image -%>
    <%= render '/refinery/admin/image_picker',
               :f => f,
               :field => :image_id,
               :image => @pod.image,
               :toggle_image_display => false %>

  </div>

  <div class='field'>
    <%= f.label :portfolio_entry_id, 'Gallery' -%>
    <%#= f.collection_select :portfolio_entry_id, ::Refinery::Portfolio::Gallery.order(:title), :id , :title, {:prompt => "-- Please select when relevant --"}, {} -%>
  </div>

  <div class='field'>
    <%= f.label :video_id -%>
    <%#= f.collection_select :video_id, ::Refinery::Videos::Video.order(:name), :id , :name, {:prompt => "-- Please select when relevant --"}, {} -%>
  </div>

  <div class="field">
    <%= f.label :pages %>
    <% ::Refinery::Page.all.each do |page| %>
      <div>
        <%= check_box_tag "pod[page_ids][]", page.id, @pod.pages.include?(page) %>
        <%= page.title %>
      </div>
    <% end %>
  </div>

  <%= render '/refinery/admin/form_actions', :f => f,
             :continue_editing => false,
             :delete_title => t('delete', :scope => 'refinery.pods.admin.pods.pod'),
             :delete_confirmation => t('message', :scope => 'refinery.admin.delete', :title => @pod.name) %>
<% end -%>
<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      page_options.init(false, '', '');
    });
  </script>
<% end %>

app/views/refinery/pods/shared/_banner_pod.html.erb
<% if pod.image.present? %>
  <div class="side_pod banner_pod">
      <% if pod.url.present? %>
          <%= link_to(image_tag(pod.image.image.thumb('280x200#c').url), pod.url) %>
      <% else %>
          <%= image_tag(pod.image.image.thumb('280x200#c').url) %>
      <% end %>
	  <div class="clear"></div>
  </div>
<% end %>

app/views/refinery/pods/shared/_content_pod.html.erb
<div class="side_pod content_pod">
    <% if pod.url.present? and pod.name.present? %>
      <h1><%= link_to(pod.name, pod.url, :class => 'title') %></h1>
    <% else %>
      <h1><div class="title"><%= pod.name %></div></h1>
    <% end %>
    <%= content_tag('div', raw(pod.body), :class => 'body') if pod.body.present? %>
</div>

app/views/refinery/pods/shared/_gallery_pod.html.erb
<div class="side_pod gallery_pod">
  <ul class="gallery_slider">
    <% pod.portfolio_entry.items.each do |item| %>
      <li>
      	<%= link_to(image_fu(item.image, '280x180#c'), item.image.url, :class => "cboxElement") %>
      </li>
    <% end if pod.portfolio_entry.present? and pod.portfolio_entry.items.present? %>
  </ul>
  <p><%= pod.name %></p>
</div>

app/views/refinery/pods/shared/_inquiry_pod.html.erb
<% @inquiry ||= ::Refinery::Inquiries::Inquiry.new %>

<div class="side_pod inquiry_pod">
  <%= simple_form_for [refinery, :inquiries, @inquiry], :html => {:class => 'form-vertical'} do |f| %>
    <%= f.input :name %>
    <%= f.input :email%>
    <%= f.input :phone %>
    <%= f.input :message ,:input_html  => {:rows=>6} %>
    <%= f.button :submit, :class => 'btn-primary' %>
  <% end %>
</div>

app/views/refinery/pods/shared/_inquriy_pod.html.erb
<% @inquiry ||= ::Refinery::Inquiries::Inquiry.new %>

<div class="side_pod inquiry_pod">
  <%= simple_form_for [refinery, :inquiries, @inquiry], :html => {:class => 'form-vertical'} do |f| %>
    <%= f.input :name %>
    <%= f.input :email%>
    <%= f.input :phone %>
    <%= f.input :message ,:input_html  => {:rows=>6} %>
    <%= f.button :submit, :class => 'btn-primary' %>
  <% end %>
</div>

app/views/refinery/pods/shared/_video_pod.html.erb
<% if pod.video.present? %>
  <div class="side_pod video_pod">
    <div class="video" targeturl="<%= pod.video.youtube_url %>">
      <%= link_to('', pod.video.youtube_url, :class => "ytlink") %>
      <%= raw(pod.video.body) %>
      <p><%= pod.video.name %></p>
    </div>
  </div>
<% end %>

app/views/shared/_banner_pod.html.erb
<% if pod.image.present? %>
  <div class="tile banner">
      <% if pod.url.present? %>
          <%= link_to(image_tag(pod.image.image.thumb('280x205').url), pod.url) %>
      <% else %>
          <%= image_tag(pod.image.image.thumb('280x205').url) %>
      <% end %>
	  <div class="clear"></div>
  </div>
  
<% end %>

app/views/shared/_content_pod.html.erb
<div class="side_pod content">
    <% if pod.url.present? and pod.name.present? %>
      <h1><%= link_to(pod.name, pod.url, :class => 'title') %></h1>
    <% else %>
      <h1><div class="title"><%= pod.name %></div></h1>
    <% end %>
    <%= content_tag('div', raw(pod.body), :class => 'body') if pod.body.present? %>
</div>

app/views/shared/_gallery_pod.html.erb
<div class="gallery_pod">
  <ul class="gallery_slider">
    <% pod.portfolio_entry.images.each do |image| %>
      <li>
        <%= image_fu(image, '280x180#c') %>
      </li>
    <% end if pod.portfolio_entry.present? and pod.portfolio_entry.images.present? %>
  </ul>
  <p><%= pod.name %></p>
</div>

app/views/shared/_pods.html.erb
<% if @page.present? and @page.pods.present? %>
  <% @page.pods.order(:position).each do |pod| %>
    <%= render :partial => "shared/#{pod.system_name}_pod", :locals => {:pod => pod} %>
  <% end %>
<% end %>

app/views/shared/_video_pod.html.erb
<% if pod.video.present? %>
  <div class="video_pod">
    <div class="video" targeturl="<%= pod.video.youtube_url %>">
      <h1><%= pod.video.name %></h1>
      <%= link_to('', pod.video.youtube_url, :class => "ytlink") %>
      <%= raw(pod.video.body) %>
    </div>
  </div>
<% end %>